#!/bin/zsh

# check if file name was provided
if [ -z "$1" ]; then
  echo "Error: A file name must be set"
  exit 1
fi

# prepare the file name w/ date suffix and title
title="$1"
file_name=$(echo "$title" | sed 's/[ \/]/-/g') # better title sanitisation
formatted_file_name=${file_name}_$(date "+%Y-%m-%d").md
# paths for vault, template, and destination file
vault_dir="/home/metin/Documents/Obsidian/Main"
template_file="$vault_dir/templates/note.md"
destination="$vault_dir/inbox/${formatted_file_name}"

# date formatted
date_str=$(date "+%Y-%m-%d")

# replace placeholders in template file w/ actual ttle and date
# using a different delim '|' to avoid issues w/ any '/' in title
sed -e "s|{{title}}|$title|g" -e "s|{{date}}|$date_str|g" "$template_file" > "$destination"

nvim "$destination"
