export ZDOTDIR="$HOME/.config/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history"
export DOTFILES="$HOME/.dotfiles"
export PATH="$ZDOTDIR/scripts:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="$PATH:~/.cargo/bin"
